name: Update Scoreboard
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  update-scoreboard:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: python tools/update_progress.py
      - name: Commit updated README
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update weekly scoreboard"
          file_pattern: README.md
