name: Validate Submission Paths
on:
  pull_request:
    branches: [ main ]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate file paths
        shell: bash
        run: |
          set -e
          BASE="origin/${{ github.event.pull_request.base.ref }}"
          git fetch --depth=1 origin "$BASE"
          FAIL=0
          while read -r file; do
            if [[ "$file" == solutions/* ]]; then
              if ! [[ "$file" =~ ^solutions/[^/]+/[0-9]{4}-W[0-9]{2}/(leetcode|baekjoon|programmers)/[^/]+\.[a-zA-Z0-9]+$ ]]; then
                echo "❌ Invalid path: $file"
                FAIL=1
              fi
            fi
          done < <(git diff --name-only "$BASE"...HEAD)
          exit $FAIL
